export const Cities = [
  { code: 'albacete', name: 'Albacete Spain' },
  { code: 'alcala', name: 'Alcala de Henares Spain' },
  { code: 'alicante', name: 'Alicante Spain' },
  { code: 'algeciras', name: 'Algeciras Spain' },
  { code: 'avila', name: 'Avila Spain' },
  { code: 'barcelona', name: 'Barcelona Spain' },
  { code: 'bilbao', name: 'Bilbao Spain' },
  { code: 'buenosaires', name: 'Buenos Aires Argentina' },
  { code: 'cadiz', name: 'Cadiz Spain' },
  { code: 'caracas', name: 'Caracas Venezuela' },
  { code: 'coslada', name: 'Coslada Spain' },
  { code: 'cuenca', name: 'Cuenca Spain' },
  { code: 'huesca', name: 'Huesca Spain' },
  { code: 'jaen', name: 'Jaen Spain' },
  { code: 'madrid', name: 'Madrid Spain' },
  { code: 'malaga', name: 'Malaga Spain' },
  { code: 'rieti', name: 'Rieti Italy' },
  { code: 'sansebastian', name: 'San Sebastian Spain' },
  { code: 'sevilla', name: 'Sevilla Spain' },
  { code: 'valencia', name: 'Valencia Spain' },
  { code: 'valladolid', name: 'Valladolid Spain' },
  { code: 'vitoria', name: 'Vitoria Spain' },
  { code: 'zaragoza', name: 'Zaragoza Spain' },
];
