export const CityEmojis = {
  albacete: [':inigo-party:', ' :inigod:', ':inigo_hot:', ':iñigru:', ':bilbao:'],
  alcala: [':andrea-sun-queen:', ':andrea_brasero:', ':andrea_calvo:', ':andrea_tactica:'],
  alicante: [':ale-bounce:', ':ale-head:', ':ale-mrclean:', ':ale-pray:', ':ale_dreamer:'],
  algeciras: [':franky-batin:', ':franky-dranky:', ':franky-jungle:', ':franky-sinatra:', ':frankycheers:'],
  avila: [
    ':jgleal-head:',
    ':lealwind:',
    ':jleal-bounce:',
    ':wii-sexy-leal:',
    ':happiest-paula-ever:',
    ':paula_bolt:',
    ':paula-encinar:',
  ],
  barcelona: [':gun-gary:', ':thug-gary:'],
  bilbao: [':inigo-party:', ' :inigod:', ':inigo_hot:', ':iñigru:', ':bilbao:'],
  buenosaires: [
    ':nacho-head:',
    ':nacho-mate:',
    ':nacho-turro:',
    ':nachoked:',
    ':nacho_archaeologist:',
    ':messi-mate:',
    ':messi_world_cup:',
    ':maureen-head:',
    ':conga-maureen-parrot:',
    ':frozen-maureen:',
  ],
  cadiz: [':golden:', ':golden-bowtie:', ':golden_christmas_shepherd:'],
  caracas: [':eli-gun:', ':eli-head:'],
  coslada: [':andrea-sun-queen:', ':andrea_brasero:', ':andrea_calvo:', ':andrea_tactica:'],
  cuenca: [':irene-head:', ':irene-writer:', ':irene_walking:'],
  huesca: [':ulises_avatar:', ':ulises_hype:'],
  jaen: [':franq_epic_shirt:', ':franq-head:', ':thinking-fran:', ':san-fran:'],
  madrid: [
    ':marina-bunny:',
    ':marina-head:',
    ':marina_delighted:',
    ':marina_reindeer:',
    ':ivan-artist:',
    ':ivan-bunny:',
    ':ivan-head-flow:',
    ':ivan_deer:',
    ':vipp-bounce:',
    ':victor-thief:',
    ':victor_arrested:',
    ':victor_artist:',
    ':laura-cooker:',
    ':laura-head-reverse:',
    ':laura_delegate:',
    ':laura_jammies:',
    ':sergio-head:',
    ':david_face:',
    ':baumann-head:',
    ':bauman-fisio:',
    ':alarcon:',
    ':excalidani:',
  ],
  malaga: [':chechu:', ':holy-chechu:', ':marcelo-head:'],
  rieti: [
    ':matteo:',
    ':matteo-artist:',
    ':matteo-farmer:',
    ':matteo-fisherman:',
    ':matteo-hips-dont-lie:',
    ':matteo-pizzaiolo:',
    ':matteo_tripalovski:',
  ],
  salamanca: [':rober:', ':rober-bunny:', ':rober-malote:', ':rober-head-flow:'],
  sansebastian: [':pablo-e-head:'],
  sevilla: [':cris-panda:'],
  valladolid: [':pablo-e-head:'],
  valencia: [
    ':alex-serra:',
    ':giner-head:',
    ':magic-giner:',
    ':betis-bounce:',
    ':betis-head:',
    ':betis_dark_knight:',
    ':librisito:',
    ':sito-head:',
    ':solesito:',
  ],
  vitoria: [':inigo-party:', ' :inigod:', ':inigo_hot:', ':iñigru:', ':bilbao:'],
  zaragoza: [':dr_yorch_riviera:', ':jota-yorch:', ':sayan-yorch:', ':yorch-bricklayer:', ':yorch_cooker:'],
};
